### PR TITLE
Use lower_camel_case consistently for fields in protobuf definitions

### PR DESCRIPTION
**Pull request by joshuagl**
We [claim](https://github.com/in-toto/attestation/blob/461c6b92b7f79f4bca73e6c69b68bf6121052221/docs/protos.md) to adhere to the protobuf programming practices, and thus should also follow the [style guide](https://protobuf.dev/programming-guides/style/#message-field-names) there.

The style guide states that message field names should be lower_snake_case, not lowerCamelCase. Our protobuf definitions are somewhat inconsistent, this PR normalises to lower_snake_case for field names in protobuf definitions.

Fixes: #250

### CODE REVIEW

**Review by marcelamelara — APPROVED** [review]
Thanks @joshuagl ! These changes shouldn't break the tests, right?

**Comment by joshuagl** [comment]
> Thanks @joshuagl ! These changes shouldn't break the tests, right?

This PR does not appear to break the tests.
Alas, the tests are already broken. I've proposed a fix in #259. With that fix and this branch combined, the tests pass.

**Comment by joshuagl** [comment]
Alas, no. The generated API does change. Presumably the changed API is not covered by current tests, though? `make go_test` succeeds after my change is merged (it even uses cached results, further indicating the changed API is not covered by the tests).

**Comment by marcelamelara** [comment]
Hmm, the changed APIs should be covered in the tests AFAIK (I wrote them), in that the tests do some (un)marshalling of RD and Statement protos. I wonder now if the JSON protobuf API used in the tests treats the updated API as equivalent? I can look into this, but since the tests are working fine, we can probably leave this for another PR.

**Comment by joshuagl** [comment]
Apologies, it turns out I was wrong. I just did a manual review of the proto changes with this series applied, you can see the diff I've reviewed in a gist https://gist.github.com/joshuagl/ae743664f4422391d6e88010b1d167c0

The Go API is unchanged: struct names remain the same

**Pull request merged**
