### PR TITLE
Stepping down as a maintainer

### PR DESCRIPTION
**Pull request by joshuagl**
I haven't meaninfully contributed to the project in some time and I don't see that changing any time soon due to work and life priorities. Thanks for the fantastic collaboration and wishing the project every success!

### CODE REVIEW

**Review by marcelamelara — APPROVED** [review]
@joshuagl Thank YOU for all of your contributions, I've really appreciated our collaboration and hope we find another opportunity to work together!

**Comment by marcelamelara** [comment]
Would you be opposed to being listed as Maintainer Emeritus? I'm happy to add that in, if you're comfortable with it.

**Comment by joshuagl** [comment]
> Would you be opposed to being listed as Maintainer Emeritus? I'm happy to add that in, if you're comfortable with it.

No opposition at all, that would be nice. Thank you.

**Comment by TomHennen** [comment]
Thank you for all your work on this Joshua!

**Comment by JustinCappos** [comment]
Should we add the Emeritus addition to this PR or just approve it as is?

**Comment by TomHennen** [comment]
> Should we add the Emeritus addition to this PR or just approve it as is?

We can probably do that in a separate PR.  No need to require more work for Joshua.

**Review by TomHennen — APPROVED** [review]

**Pull request merged**
